### PR TITLE
Add option for session cookie

### PR DESCRIPTION
**Pull request by petermoresi**
Add option to expire cookie with browser session:

app.use( session( { session: true }, app ) )

### CODE REVIEW

**Comment by dead-horse** [comment]
why not just set `{maxAge: null}` ?

**Comment by petermoresi** [comment]
`{ maxAge: null }` sets the expiry to ONE_DAY.

See line 285:
`var maxAge = opts.maxAge || ONE_DAY;`

**Comment by petermoresi** [comment]
I am ok with the configuration `{maxAge: null}`

Perhaps line 285 could be changed to:

`var maxAge = opts.maxAge === null ? null : (opts.maxAge || ONE_DAY);`

**Comment by petermoresi** [comment]
I tried setting `{maxAge: null}` with this code change but it didn't work.

**Comment by petermoresi** [comment]
This change isn't working. I will reopen when I have it figured out

**Pull request closed without merging**
