### PR TITLE
fix: RFC6265 compliant default cookie name

### LINKED ISSUE #28: Default cookie name doesn't satisfy RFC6265
The default cookie name [`koa:sess`](https://github.com/koajs/session/blob/master/index.js#L21) contains `:`, which is not a valid token character in accordance with [RFC6265](https://tools.ietf.org/html/rfc6265#section-4.1.1) and [RFC2616](https://tools.ietf.org/html/rfc2616#section-2.2). Although most web browsers and servers allow this, it causes problems in some more strict environment such as [spray](http://spray.io).

Would you consider remaining it? If so, should we take backward compatibility into account?

### PR DESCRIPTION
**Pull request by zacanger**
Closes #28

### CODE REVIEW

**Comment by dead-horse** [comment]
we can't merge this right now because It can break compatibility, maybe you can add a note in README ?

**Comment by zacanger** [comment]
@dead-horse good point. Should that go in History.md instead as a major version note?

**Comment by jonathanong** [comment]
@zacanger yep.

we can do a major bump - we shouldn't be afraid to do those

**Comment by zacanger** [comment]
Changelog updated!

**Comment by dead-horse** [comment]
6.0.0 released

**Comment by zacanger** [comment]
Sorry about the package-lock, I forgot Koa repos don't use that.

**Pull request merged**
